### ISSUE TITLE
調整授權

### ISSUE THREAD

**Issue by virus-warnning** [OsmHackTW/Geomancer#48]
改回較寬鬆的授權，做在 Issue #37 的頁面上

**Comment by chihchun** [comment]
mapsforge 是 LGPL 3 授權，你的主程式不需要是 GPL 3 or LGPL 3 授權。
- License change from GPL3 to LGPL3.  - https://github.com/mapsforge/mapsforge/blob/master/docs/Changelog.md
- License change from GPL3 to LGPL3 - Google 網上論壇 - https://groups.google.com/d/msg/mapsforge-dev/WWJVjZwc2OM/jgeSM5RTN-8J

**Comment by virus-warnning** [comment]
謝謝你，我去複習一下
